[build]
  publish = "dist"
  functions = "netlify/functions"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# API 프록시 리다이렉트
[[redirects]]
  from = "/.netlify/functions/api-proxy/*"
  to = "/.netlify/functions/api-proxy/:splat"
  status = 200

# SPA 리다이렉트
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 