[build]
  publish = "dist"
  functions = "netlify/functions"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

# SPA 리다이렉트
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200